import { LucideIcon } from 'lucide-react';

// --- Session and Component Types ---
export type SessionStatus = 'running' | 'idle' | 'paused' | 'completed' | 'failed';
export type ComponentType = 'attack-testing' | 'defense-testing';

// --- Attack Types ---
export type AttackType = 'single' | 'chain';
export type AttackStatus = 'success' | 'partial' | 'blocked';

// --- Log Types ---
export type LogType = 'pass' | 'block';

// --- Component Labels ---
export interface ComponentLabel {
  name: string;
  icon: LucideIcon;
  color: string;
}

// --- Run Summary and Template Types ---
export interface Run { // Summary interface for a list of runs
  id: string;
  name: string;
  description: string;
  components: ComponentType[];
  status: SessionStatus;
  lastActive: string;
  created: string;
}

export interface RunTemplate {
  name: string;
  description: string;
  components: ComponentType[];
}

// --- Attack Prompt and Defense Log Types ---
export interface AttackPrompt {
  id: number; // Consider using string IDs if generated by backend
  type: AttackType;
  timestamp: string;
  status: AttackStatus;
  prompts: string[]; // This might need to be more structured, e.g., { original: string, generated: string }
}

export interface DefenseLog {
  id: number; // Consider using string IDs
  type: LogType;
  layer: string;
  prompt: string;
  result: string;
  time: string;
}

// --- Configuration Types ---
export interface AttackConfig {
  model: string;
  temperature: number;
  max_tokens: number;
  prompts?: string[]; // This might be redundant if AttackPrompts holds the generated ones
  strategy?: string; // e.g., 'single-turn', 'multi-turn'
  max_retries?: number;
}

export interface BackendConfig {
  url: string;
  apiKey?: string;
}

export interface DefenseLayer {
  id: string;
  type: string;
  name: string;
  enabled: boolean;
  order: number;
}

export interface DefenseStats {
  blockedAttacks: number;
  passedLegitimate: number;
  accuracy: number;
}

export interface DefenseBackendConfig {
  url: string;
  // Add other defense-specific configurations if needed
}

export interface DataStorageConfig {
  type: 'local' | 'remote';
  path?: string;
}

// --- Detailed Run State and Evaluation Types ---
export interface EvaluationResult {
  id: string; // Consider using string IDs
  runId: string; // Link back to the run
  attackPrompt: string; // The prompt that was sent
  defenseResponse: string; // The response from the defender
  evaluation: string; // e.g., "breached", "blocked"
  reasoning: string; // Judge's explanation
  timestamp: string;
}

// Represents the detailed state of a single run
export interface RunState {
  id: string;
  name: string;
  description: string;
  status: SessionStatus;
  created: string;
  lastActive: string;
  // Configurations specific to this run
  attackConfig: AttackConfig;
  defenseConfig: DefenseBackendConfig; // Assuming DefenseBackendConfig is sufficient for now
  // Detailed logs and results for this run
  attackPrompts: AttackPrompt[];
  defenseLogs: DefenseLog[];
  evaluationResults: EvaluationResult[];
  // Any other run-specific data
  // e.g., metadata for LLM generation, strategy details
  strategyMetadata?: Record<string, any>;
}

// We can keep the existing Run interface for a summary list of runs,
// but RunState will hold the detailed, mutable state for active runs.

// Update the existing Run interface to potentially use RunState or a subset of it
// For now, let's assume Run is a summary and RunState is the detailed view.
// If Run is meant to be the detailed state, we'll adjust.


export interface RunsStateData {
  runs: Record<string, RunState>;
  activeRunId: string | null;
}

export interface RunsStateActions {
  setRuns: (runs: Record<string, RunState>) => void;
  addRun: (run: RunState) => void;
  updateRun: (id: string, updatedRun: Partial<RunState>) => void;
  deleteRun: (id: string) => void;
  setActiveRun: (id: string | null) => void;
}

export type RunsState = RunsStateData & RunsStateActions;
export interface GlobalConfigData {
  backendConfig: BackendConfig;
  dataStorageConfig: DataStorageConfig;
}

export interface GlobalConfigActions {
  setBackendConfig: (config: BackendConfig) => void;
  setDataStorageConfig: (config: DataStorageConfig) => void;
}

export type GlobalConfigState = GlobalConfigData & GlobalConfigActions;

// Root state interface combining all states
export interface AppState {
  runsState: RunsState;
  globalConfigState: GlobalConfigState;
  // Add other global states as needed
}
